---
title: "ICE 5"
author: "Yangzhi Xu"
date: "4/28/2022"
output: html_document
---

#Missing data mechanism
```{r}
library(datasets)
data(iris)
head(iris)
```
#MCAR
```{r}
iris_MCAR <- iris

missing_fraction <- 0.3 #faction of missing variables 
N <- nrow(iris_MCAR)

is.na(iris_MCAR[sample.int(N, missing_fraction*N), "Sepal.Length"]) <- TRUE

iris_MCAR
```
#MAR
```{r}
logit <- function(x){log(x/(1-x))}
invlogit <- function(x){1/(1+exp(-x))}

m.SW <- mean(iris$Sepal.Width)
pmiss <- invlogit(iris$Sepal.Width -m.SW + logit(0.3))
hist(pmiss) 

iris_MAR <- iris
N <- nrow(iris_MAR)
is.na(iris_MAR$Sepal.Length[runif(N) < pmiss]) <- TRUE

iris_MAR
```
#Listwise deletion
```{r}
iris_MCAR_listwise <- iris_MCAR[complete.cases(iris_MCAR),]
nrow(iris_MCAR_listwise)
```
#Pairwise deletion
```{r}
mean(iris_MCAR$Sepal.Length, na.rm = TRUE)
sd(iris_MCAR$Sepal.Length, na.rm = TRUE)
```
#Simple imputation
```{R}
iris_MCAR_mean <- iris_MCAR
mi <- mean(iris_MCAR$Sepal.Length, na.rm = TRUE)
iris_MCAR_mean$Sepal.Length[is.na(iris_MCAR$Sepal.Length)] <- mi
iris_MCAR_mean
```
#Regression Imputation/Conditional Mean Imputation
```{r}
iris_MAR_regression <- iris_MAR
lm_model <- lm(Sepal.Length ~ Sepal.Width, iris_MAR_regression)
summary(lm_model)

iris_MAR_regression$Sepal.Length[is.na(iris_MAR$Sepal.Length)] <- -0.08 * iris_MAR_regression$Sepal.Width[is.na(iris_MAR$Sepal.Length)] + 6.085

iris_MAR_regression
```
